azs:
- name: z1
  cloud_properties:
    availability_zone: eu-west-1a


vm_types:
- name: small
  cloud_properties:
    instance_type: t2.small
    availability_zone: eu-west-1a
- name: compiler
  cloud_properties:
    instance_type: c4.large
    availability_zone: eu-west-1a


disk_types:
- name: default
  disk_size: 5000
  cloud_properties:
    type: standard


compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: compiler
  network: private


networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    reserved: [10.0.2.1 - 10.0.2.6]
    static: [10.0.2.10 - 10.0.2.20]
    azs: [z1]
    cloud_properties:
      subnet: subnet-8812c6d2
      security_groups: [cf-training-mosesbosire2-bosh]

- name: public
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    reserved: [10.0.1.1 - 10.0.1.6]
    static: [10.0.1.10 - 10.0.1.20]
    azs: [z1]
    cloud_properties:
      subnet: subnet-be16c2e4
      security_groups: [cf-training-mosesbosire2-bosh]

- name: eip
  type: vip
